;; popwin
;; (setq pop-up-windows nil)
(when (require 'popwin nil t)
  ;; (setq display-buffer-function 'popwin:display-buffer)
  (popwin-mode 1)
  (setq popwin:popup-window-height 0.4)
  (setq anything-samewindow nil)
  (push '("*my-anything*") popwin:special-display-config)
  ;; (push '("*my-anything*" :height 20) popwin:special-display-config)
  ;; (push '("*anything mini*" :height 20) popwin:special-display-config)
  (push '("*Warnings*" :height 20) popwin:special-display-config)
  (push '(dired-mode :position top) popwin:special-display-config)
  ;; (push '("anything" :regexp t :height 0.5) popwin:special-display-config)
  ;; (push '("*anything*" :height 20) popwin:special-display-config)
  (push '("*cider-doc*" :height 0.5) popwin:special-display-config)
  (push '("*cider-error*" :height 0.5) popwin:special-display-config)
  (push '("*Completions*" :height 0.5) popwin:special-display-config)
  (push '("*compilation*" :height 0.5) popwin:special-display-config)
  (push '("*magit-edit-log*" :height 0.5) popwin:special-display-config)
  ;; M-!
  (push "*Shell Command Output*" popwin:special-display-config)
  (push '("*quickrun*") popwin:special-display-config)
  (push '("*Org Agenda*") popwin:special-display-config)
  (push '("*Help*") popwin:special-display-config)
  )

(provide 'setup-popwin)
